# Generated by Django 3.1.3 on 2020-11-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20201107_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
