# Generated by Django 3.1.3 on 2020-11-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20201107_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_ultima_sesion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
