# Generated by Django 3.1.3 on 2020-11-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.CharField(blank=True, max_length=40, primary_key=True, serialize=False)),
                ('borrado', models.BooleanField(default=False)),
                ('observaciones', models.CharField(default='', max_length=5000, verbose_name='observaciones')),
                ('notas', models.CharField(blank=True, default='', max_length=5000, null=True, verbose_name='notas')),
                ('image', models.FileField(blank=True, null=True, upload_to='uploads')),
                ('fecha_creacion', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
