# Generated by Django 3.1.3 on 2020-11-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='notas',
            field=models.CharField(default='', max_length=5000, verbose_name='notas'),
        ),
    ]
