# Generated by Django 3.1.3 on 2020-11-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0002_auto_20201107_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='notas',
            field=models.CharField(blank=True, default='', max_length=5000, null=True, verbose_name='notas'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='observaciones',
            field=models.CharField(blank=True, default='', max_length=5000, null=True, verbose_name='observaciones'),
        ),
    ]
